export type Skill = {
  name: string;
  category: string;
  desc: string;
  prompt: string; // 选中后自动填入输入框的提示词模版
};

// 技能目录：每个技能本质上是一个 prompt 模版，选中后自动贴入输入框。
export const SKILLS: Skill[] = [
  { name: "skill-creator", category: "创作", desc: "创建、修改并优化你自己的技能。",
    prompt: "帮我创建一个新的技能（skill）。\n技能用途：\n输入：\n期望输出：" },
  { name: "find-skills", category: "创作", desc: "根据需求发现并安装合适的技能。",
    prompt: "我想做这件事：\n请帮我找到并推荐最合适的技能。" },
  { name: "frontend-slides", category: "内容", desc: "生成动效丰富的 HTML 幻灯片演示。",
    prompt: "帮我制作一份动效丰富的 HTML 幻灯片。\n主题：\n页数：\n风格：" },
  { name: "ai-slide-deck", category: "内容", desc: "按主题自动生成带配图的演示文稿。",
    prompt: "帮我生成一份带配图的演示文稿。\n主题：\n受众：\n关键要点：" },
  { name: "canvas-design", category: "设计", desc: "用设计理念产出精美的 PNG / PDF 视觉稿。",
    prompt: "帮我设计一张精美视觉稿（输出 PNG/PDF）。\n用途：\n文案：\n风格偏好：" },
  { name: "frontend-design", category: "设计", desc: "生成高质量、可上线的前端界面。",
    prompt: "帮我设计一个前端页面。\n页面类型：\n核心功能：\n风格参考：" },
  { name: "infographic-creator", category: "设计", desc: "把文字内容做成精美信息图。",
    prompt: "帮我把下面的内容做成一张精美信息图：\n" },
  { name: "generate-image", category: "图像", desc: "调用多模型生成图片（FLUX / Gemini 等）。",
    prompt: "帮我生成一张图片。\n主题/描述：\n风格：\n尺寸比例：" },
  { name: "nano-banana-pro", category: "图像", desc: "用 Gemini 3 Pro Image 生成或编辑图片。",
    prompt: "用 Nano Banana Pro 帮我生成/编辑图片：\n描述：" },
  { name: "bg-remover", category: "图像", desc: "AI 智能抠图，去除背景、提取主体。",
    prompt: "帮我对这张图片进行抠图（去除背景），保留主体：\n（请上传图片）" },
  { name: "generate-video", category: "视频", desc: "调用 Veo / Seedance 等模型生成视频。",
    prompt: "帮我生成一段视频。\n画面描述：\n时长：\n风格：" },
  { name: "storyboard-to-film", category: "视频", desc: "从故事概念到成片的动画短片流水线。",
    prompt: "帮我把这个故事做成一段动画短片：\n故事概念：" },
  { name: "pptx", category: "办公", desc: "创建、读取、编辑 PowerPoint 文件。",
    prompt: "帮我制作一份 PowerPoint（.pptx）。\n主题：\n章节：" },
  { name: "docx", category: "办公", desc: "创建、读取、编辑 Word 文档。",
    prompt: "帮我撰写一份 Word 文档（.docx）。\n标题：\n内容要点：" },
  { name: "xlsx", category: "办公", desc: "处理电子表格，读写 Excel 数据。",
    prompt: "帮我处理电子表格（.xlsx）。\n需求：\n（如有数据请上传）" },
  { name: "pdf", category: "办公", desc: "读取、提取、合并、生成 PDF 文件。",
    prompt: "帮我处理 PDF。\n需求（提取/合并/生成/转换）：\n（请上传文件）" },
  { name: "latex-document", category: "办公", desc: "用 LaTeX 排版生成专业 PDF 文档。",
    prompt: "帮我用 LaTeX 排版一份专业 PDF 文档。\n类型（论文/简历/报告）：\n内容：" },
  { name: "data-storytelling", category: "数据", desc: "把数据转化为有说服力的可视化叙事。",
    prompt: "帮我把这组数据做成可视化叙事：\n数据/背景：" },
  { name: "chart-visualization", category: "数据", desc: "智能选择图表类型可视化你的数据。",
    prompt: "帮我可视化下面的数据，自动选择合适的图表：\n数据：" },
  { name: "comprehensive-researcher", category: "研究", desc: "对任意主题进行深入的多源研究。",
    prompt: "帮我深入研究并总结一个主题：\n主题：\n我关心的问题：" },
  { name: "web-search", category: "研究", desc: "联网搜索并给出 AI 摘要。",
    prompt: "帮我联网搜索并总结：\n查询：" },
  { name: "world-class-carousel", category: "内容", desc: "生成世界级的 Instagram 多图文内容。",
    prompt: "帮我生成一组 Instagram 多图文（carousel）。\n主题：\n目标受众：" },
  { name: "happycapy-feishu", category: "集成", desc: "接入飞书 MCP，操作消息 / 文档 / 多维表格。",
    prompt: "帮我接入飞书（Lark）MCP，我想做的操作是：" },
  { name: "gmail", category: "集成", desc: "Gmail 集成，读取、发送、管理邮件。",
    prompt: "用 Gmail 帮我处理邮件。\n需求（读取/发送/整理）：" },
  { name: "notion", category: "集成", desc: "Notion API，创建管理页面与数据库。",
    prompt: "用 Notion 帮我创建/管理内容。\n需求：" },
  { name: "capymail", category: "集成", desc: "用 Capy 发送邮件。",
    prompt: "帮我用 Capymail 发一封邮件。\n收件人：\n主题：\n正文：" },
  { name: "weather", category: "工具", desc: "查询实时天气与预报，无需 API Key。",
    prompt: "帮我查一下天气：\n城市：" },
  { name: "currency-converter", category: "工具", desc: "实时汇率换算。",
    prompt: "帮我做汇率换算：\n金额与货币（如 100 USD → CNY）：" },
  { name: "github-push", category: "工具", desc: "把本地项目或文件推送到 GitHub。",
    prompt: "帮我把项目推送到 GitHub。\n仓库：\n分支：" },
  { name: "readme-generator", category: "工具", desc: "为仓库生成专业的 README。",
    prompt: "帮我为这个项目生成一份专业的 README。\n项目简介：" },
];

export const CATEGORIES = ["全部", "创作", "内容", "设计", "图像", "视频", "办公", "数据", "研究", "集成", "工具"];
